const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';

const FETCH_CUSTOMERS_REQUEST = 'FETCH_CUSTOMERS_REQUEST';
const FETCH_CUSTOMERS_FAILURE = 'FETCH_CUSTOMERS_FAILURE';
const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';